services:
  glance:
    build:
      context: .
      dockerfile: Dockerfile.single-platform
    container_name: glance
    volumes:
      - ./:/app
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8080:8080
    restart: unless-stopped
